### PR TITLE
Fixed file input to allow various file types

### LINKED ISSUE #786: Fix Program Managers uploading pngs to events
When Program Managers attempt to upload png posters to events they are thrown a "system error". Investigate where it is coming from and fix.

### PR DESCRIPTION
**Pull request by martinj2-dot**
Issue #786  Added the ability to upload various relevant file types. Maybe we should ask them what types of files they mostly would like to upload.  

To Test:
Navigate to edit or create event and try to upload any file type. 
As of now it should only accept files with these extensions: "pdf","jpg","png","gif", "csv", "docx"

### CODE REVIEW

**Review by tylerpar99 — DISMISSED** [review]

File: app/static/js/createEvents.js [hunk 1]
```diff
@@ -37,7 +37,9 @@ function format24to12HourTime(timeStr){
  * Run when the webpage is ready for javascript
  */
 $(document).ready(function() {
-    $("#attachmentObject").fileinput()
+    $("#attachmentObject").fileinput({
+        allowedFileExtensions:["pdf","jpg","png","gif", "csv", "docx"]
```
Comment (tylerpar99) [inline app/static/js/createEvents.js]: Looks good only snag is we want to add `jpeg` just another common image file type.

**Review by tylerpar99 — APPROVED** [review]

**Review by tylerpar99 — APPROVED** [review]
